language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install lattice base64enc knitr markdown shiny digest codetools hexbin ggplot2 jsonlite fastICA scagnostics magrittr dplyr testthat roxygen2
  - ./travis-tool.sh install_github tesseradata/datadr rstudio/shinyapps
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients:
    - rhafen@gmail.com
    on_success: change
    on_failure: change
